### ISSUE TITLE
DVWA, PHP version: 7.0.16-3 - Blank dvwa/setup.php page

### ISSUE THREAD

**Issue by ghigliottyc** [ethicalhack3r/DVWA#157]
Hi all,

I've been trying to debug this issue for the past few days with no luck. System check doesn't report any errors, but when I try to create/reset the database on http://127.0.0.1/dvwa/setup.php# I'm greeted with a blank page. 

Setup Check
Operating system: *nix
Backend database: MySQL
PHP version: 7.0.16-3

Web Server SERVER_NAME: 127.0.0.1

PHP function display_errors: Disabled
PHP function safe_mode: Disabled
PHP function allow_url_include: Enabled
PHP function allow_url_fopen: Enabled
PHP function magic_quotes_gpc: Disabled
PHP module php-gd: Installed

reCAPTCHA key: 

Writable folder /var/www/html/dvwa/hackable/uploads/: Yes)
Writable file /var/www/html/dvwa/external/phpids/0.6/lib/IDS/tmp/phpids_log.txt: Yes

Anyone else encounter this issue?

**Comment by digininja** [comment]
have you checked the Apache error logs?

**Comment by ghigliottyc** [comment]
Hey @digininja,

Sorry should I dropped those in here too.

I'm attempting to run this in a Kali Linux VM

127.0.0.1 - - [23/May/2017:09:10:19 -0400] "POST /dvwa/setup.php HTTP/1.1" 500 295 "http://127.0.0.1/dvwa/setup.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [23/May/2017:09:10:19 -0400] "GET /favicon.ico HTTP/1.1" 404 501 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [23/May/2017:09:17:42 -0400] "GET /dvwa/login.php HTTP/1.1" 500 295 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [23/May/2017:09:22:11 -0400] "POST /dvwa/setup.php HTTP/1.1" 500 295 "http://127.0.0.1/dvwa/setup.php" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
127.0.0.1 - - [23/May/2017:09:46:33 -0400] "POST /dvwa/setup.php HTTP/1.1" 500 295 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"

**Comment by mike-bailey** [comment]
I could be mistaken but that looks like the access log, not error logs?

**Comment by digininja** [comment]
500 is internal server error, send us the error logs as well. And turn on
displaying errors so you can see them on screen as well.

**Comment by ghigliottyc** [comment]
Yup, you're right.

Error logs:

Mon May 22 08:56:12.516751 2017] [:error] [pid 3441] [client 127.0.0.1:40138] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://127.0.0.1/dvwa/setup.php
[Mon May 22 08:56:26.874598 2017] [:error] [pid 3443] [client 127.0.0.1:40142] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://127.0.0.1/dvwa/setup.php
[Mon May 22 08:59:31.225975 2017] [:error] [pid 3444] [client 127.0.0.1:40144] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php:9\nStack trace:\n#0 /var/www/html/dvwa/setup.php(17): include_once()\n#1 {main}\n  thrown in /var/www/html/dvwa/dvwa/includes/DBMS/MySQL.php on line 9, referer: http://127.0.0.1/dvwa/setup.php

I was looking at the MySQL.php file and this is the referenced function:

`if(` !@mysql_connect( $_DVWA[ 'db_server' ], $_DVWA[ 'db_user' ], $_DVWA[ 'db_password' ] ) ) {
	dvwaMessagePush( "Could not connect to the database.<br/>Please check the config file." );
	dvwaPageReload();
}`

**Comment by happsdev** [comment]
You may have to change mysql_connect to mysqli_connect in the config. Are you getting a blank page or unable to connect to the database when you try on the setup page? Has it ever worked or is this a new setup?

**Comment by digininja** [comment]
What version are you using? We should have got rid of all instances of
mysql_connect by now.

**Comment by happsdev** [comment]
Yeah I thought most of the old stuff was replaced last year?

**Comment by ghigliottyc** [comment]
@happsdev this is an entirely new set-up. I tried changing mysql_connect to mysqli_connect in the config file, issue persists.

@digininja - I'm using v 1.9

Thank you both for your help

**Comment by digininja** [comment]
That has been fixed for ages:

https://github.com/ethicalhack3r/DVWA/blob/master/dvwa/includes/DBMS/MySQL.php

Grab the latest from the github repo, that should work fine.

**Comment by mike-bailey** [comment]
_Please note after this message if there's been no activity on this issue in two weeks the issue will be closed._

**Comment by Beeq1** [comment]
my DVWA website is not working it just gives me a blank screen and nothing iv checked my apache logs and this is what I got

w/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php:545\nStack trace:\n#0 /var/www/html/dvwa-1.0.8/login.php(9): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php on line 545
[Wed Oct 04 16:06:15.470018 2017] [:error] [pid 9430] [client ::1:45066] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php:545\nStack trace:\n#0 /var/www/html/dvwa-1.0.8/login.php(9): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php on line 545
[Wed Oct 04 16:07:25.760080 2017] [:error] [pid 9431] [client 127.0.0.1:33500] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php:545\nStack trace:\n#0 /var/www/html/dvwa-1.0.8/login.php(9): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php on line 545
[Wed Oct 04 16:08:05.717324 2017] [:error] [pid 9472] [client 127.0.0.1:33524] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php:545\nStack trace:\n#0 /var/www/html/dvwa-1.0.8/login.php(9): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php on line 545
[Wed Oct 04 16:35:43.068540 2017] [:error] [pid 9427] [client 127.0.0.1:33552] PHP Fatal error:  Uncaught Error: Call to undefined function mysql_connect() in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php:545\nStack trace:\n#0 /var/www/html/dvwa-1.0.8/login.php(9): dvwaDatabaseConnect()\n#1 {main}\n  thrown in /var/www/html/dvwa-1.0.8/dvwa/includes/dvwaPage.inc.php on line 545





please help

**Comment by digininja** [comment]
Any mention of mysql_connect means you are using a very out of date
version. Get the latest version.

**Comment by mike-bailey** [comment]
In fact, it explicitly says what version:
>1.0.8
Which is definitely out of date.
